wmcadigital/wmn-design-system

src/assets/sass/_mixins.scss, src/views/www/pages/styles/colour-palettes/_color-palette-macro.njk, src/views/www/pages/styles/colour-palettes/_color-palettes.js, src/views/www/pages/styles/colour-palettes/_colorPalette.scss, src/views/www/pages/styles/colour-palettes/index.njk, src/views/www/wmnds-website.scss
=> Fix: colours disappeared on colour palettes page

src/www/pages/styles/typography/index.njk
Closing Link incorrect on Typography page
=> Corrected link

src/www/pages/components/form-elements/index.njk
Add radio button documentation
=> MP - Add documentation to radio buttons

src/wmnds/components/content-tiles/travel-tips/_travel-tips.scss, src/wmnds/components/content-tiles/travel-tips/travel-tips.njk, src/www/pages/components/content-tiles/index.njk
Removed nunjucks refs to help component and updated travel tip background colour in css
=> Updated bg colour for travel tip component fixes #227

src/www/_layouts/layout-fullwidth.njk
It fixes https://github.com/wmcadigital/wmn-design-system/issues/290
=> Update main content (#290)

src/wmnds/components/form-elements/radios/_radios.njk, src/wmnds/components/form-elements/radios/_radios.scss, src/www/pages/components/form-elements/index.njk
=> modifier to make radio buttons display inline

src/www/wmnds-website.js
Hex codes were missing from the colour page in styles section.
Fixes #305
=> Bugfix for hex colour value (#305)

src/wmnds/components/content-tiles/normal/_normal.scss, src/wmnds/components/form-elements/_form-elements.scss, src/wmnds/components/form-elements/file-upload/_file-upload.njk, src/wmnds/components/form-elements/file-upload/_file-upload.scss, src/www/pages/components/form-elements/index.njk
Fixes #281 
Ignore the change to src/wmnds/components/content-tiles/normal/_normal.scss it should be fine but it was a commit from the previous branch, not sure why it committed again.
=> Added file upload component

src/wmnds/assets/sass/_vars.scss, src/wmnds/components/_components.scss, src/wmnds/components/table/_table.njk, src/wmnds/components/table/_table.scss, src/www/data.njk.json, src/www/pages/components/table/index.njk
=> Added new table component

src/wmnds/components/_components.scss, src/wmnds/components/text-editor-elements/_text-editor-elements.scss, src/wmnds/components/text-editor-elements/in-text-step/_in-text-step.njk, src/wmnds/components/text-editor-elements/in-text-step/_in-text-step.scss, src/www/data.njk.json, src/www/pages/components/text-editor-elements/index.njk
- Added in-text step component
- Added text editor elements directory
fixes #316
=> Added in-text step component

src/wmnds/patterns/footer/_footer.scss, src/www/_partials/component-example/_component-example.scss, src/www/_partials/component-example/component-example.njk
=> Fix background extension of footer.

src/wmnds/patterns/header/_header.njk
=> Remove phase indicator from header

src/wmnds/components/content-tiles/normal/_normal.scss
Fix issues with long texts on "read more" anchor.
Fixes #201 
Fixes #208 (@daylesalmon could you double-check if it is completely sorted)
=> Fix read more bug.

src/www/pages/components/breadcrumb/index.njk
=> Add unique aria-labels to breadcrumb component examples

src/www/pages/patterns/header-and-footer/index.njk
Added missing links to documentation. Fixes #355
=> Add links to Header and Footer documentation

src/wmnds/components/file-download/_file-download.scss
=> Remove whitespace in file-download.scss

src/www/pages/patterns/contact-details/index.njk
=> Add escaped double quotes

src/wmnds/components/link/link/_link.njk, src/www/pages/components/links/index.njk
=> Add back link to links component.

src/wmnds/assets/sass/_utilities.scss, src/wmnds/components/form-elements/checkboxes/_checkboxes.scss
Changed checkbox container to display block and used padding for vertical alignment,
fixed double quotes error
=> fix checkbox issue, fix console error

src/wmnds/patterns/header-v2/_header-v2.njk, src/wmnds/patterns/header-v2/_header-v2.scss, src/www/pages/patterns/header-v2/index.njk
fixes #408
updated mega menu and design system example as per user research recommendations
=> Mega menu updates

src/wmnds/components/table/_table.njk, src/wmnds/components/table/_table.scss, src/www/pages/components/table/index.njk
Implement two differents methods for using tables on mobile. Add option to define tables header.
Fixes #406
=> Implement two differents methods for using tables on mobile.

src/www/pages/patterns/header-v2/index.njk
Recomended JS in the Header V2 component example was slightly out of date. This was missed in the PR merge
=> Updated js in header v2 component example

src/wmnds/components/accordion/_accordion.njk, src/wmnds/components/accordion/_accordion.scss
=> Vertically align Accordion titles

src/wmnds/components/button/_button.scss, src/www/pages/components/buttons/index.njk
=> Add dark background button variants

src/wmnds/components/link/link/_link.njk, src/wmnds/components/link/link/_link.scss, src/www/pages/components/links/index.njk
=> Add Link with chevron section

src/www/data.njk.json, src/www/pages/styles/images/index.njk
=> Add images documentation page

src/wmnds/assets/sass/_mixins.scss, src/wmnds/components/lists/ordered-list/_ordered-list.scss, src/wmnds/components/lists/unordered-list/_unordered-list.scss
=> Add indentation for long list content

src/wmnds/assets/sass/_utilities.scss, src/www/_layouts/_master-layout.njk
=> make design system footer stick to bottom

src/wmnds/assets/sass/_mixins.scss, src/wmnds/assets/sass/_typography.scss
=> Added type settings/styles for h5/h6

.github/ISSUE_TEMPLATE/question.md, src/www/_partials/component-example/component-example.njk
- Added a loop which adds another table of options for each property with arrayOptions
=> feat: display options for array type properties

src/wmnds/components/form-elements/checkboxes/_checkboxes.njk, src/wmnds/components/form-elements/question/_example.njk, src/wmnds/components/form-elements/question/_properties.njk.json, src/wmnds/components/form-elements/question/_question.njk, src/wmnds/components/form-elements/radios/_radios.njk, src/wmnds/patterns/question/reference/_reference.njk, src/wmnds/patterns/question/summary/_summary.njk, src/www/data.njk.json, src/www/pages/components/form-elements/index.njk.md, src/www/pages/components/question/index.njk.md
- Added properties and examples for wmndsQuestion component
- updated param label to contentText across code
- moved component to new page
=> feat: form elements - question documentation

src/wmnds/components/form-elements/progress-indicator/_example.njk, src/wmnds/components/form-elements/progress-indicator/_progress-indicator.njk, src/wmnds/components/form-elements/progress-indicator/_properties.njk.json, src/wmnds/patterns/question/reference/_reference.njk, src/www/data.njk.json, src/www/pages/components/form-elements/index.njk.md, src/www/pages/components/progress-indicator/index.njk.md
- Added properties and examples for wmndProgressIndicator component
- updated param label to currentSection
- moved component to new page
=> feat: form elements - progress indicator documentation

src/wmnds/components/form-elements/file-upload/_example.njk, src/wmnds/components/form-elements/file-upload/_file-upload.njk, src/wmnds/components/form-elements/file-upload/_file-upload.scss, src/wmnds/components/form-elements/file-upload/_properties.njk.json, src/www/data.njk.json, src/www/pages/components/file-upload/index.njk.md
- Moved component to a new page
- Added properties and examples for wmndsFileUpload component
- No references to be updated
- Updated File upload params
- Grouped params: error message params, group params (no label, no hint and no attributes)
=> feat: form elements - File upload documentation

src/wmnds/assets/sass/_mixins.scss, src/wmnds/assets/sass/styles/_lists.scss, src/www/wmnds-website.scss
Fixes #628 issues raised by @mrmjprice.
=> fix: Updated margins on headings and lists to improve readability

src/www/pages/components/buttons/index.njk.md, src/www/pages/patterns/question-form/index.njk
=> fix: Change CTA button size to be text width within forms

src/wmnds/patterns/header-v2/_header-v2.njk, src/www/data.njk.json
=> fix: Removed "down arrow" icons from main nav within the design system

src/wmnds/assets/sass/styles/_lists.scss, src/wmnds/components/breadcrumb/_breadcrumb.njk, src/wmnds/patterns/header-v2/_header-v2.njk
=> fix: Remove duplicated breadcrumbs on hub pages

src/wmnds/patterns/question/form-element/_form-element.njk, src/wmnds/patterns/question/reference/_reference.njk, src/wmnds/patterns/question/summary/_summary.njk, src/www/pages/patterns/question-form/index.njk
Update all form patterns examples:
- padding (from sm/md -> lg)
- form width
- input width
Fixes #677
=> fix: apply a few design changes to the question form pattern.

src/wmnds/components/_components.scss, src/wmnds/components/ticket-summary-message/_example.njk, src/wmnds/components/ticket-summary-message/_properties.njk.json, src/wmnds/components/ticket-summary-message/_ticket-summary-message.njk, src/wmnds/components/ticket-summary-message/_ticket-summary-message.scss, src/www/data.njk.json, src/www/pages/components/ticket-summary-message/index.njk.md
=> feat: add ticket summary message component

src/www/pages/patterns/question-form/index.njk
=> fix: replace ampersand on form button text

src/wmnds/patterns/header-v2/_header-v2.scss
=> fix: CSS bug that caused a gap on mobile nav when search was open.

src/wmnds/components/icon/_icon.njk, src/wmnds/patterns/header-v2/_header-v2.njk
Fixes #729 
Direct link: https://deploy-preview-732--wmnetwork.netlify.app/patterns/header/
=> fix: Update header2 example

src/www/pages/404.njk.md
updated 404 copy
https://zpl.io/2ygzX3K
fixes #684
=> fix: amend 404 copy

src/wmnds/assets/sass/_vars.scss
=> fix: Replace sustainable color in order to meet colour contrast standards.

src/wmnds/assets/sass/styles/_utilities.scss, src/wmnds/components/button/_button.njk, src/wmnds/components/button/_button.scss, src/wmnds/components/form-elements/dropdown/_dropdown.njk, src/wmnds/patterns/_patterns.scss, src/wmnds/patterns/journey-planner-widget/_example.js, src/wmnds/patterns/journey-planner-widget/_example.njk, src/wmnds/patterns/journey-planner-widget/_journey-planner-widget.njk, src/wmnds/patterns/journey-planner-widget/_journey-planner-widget.scss, src/wmnds/patterns/journey-planner-widget/_properties.njk.json, src/www/data.njk.json, src/www/pages/patterns/journey-planner-widget/index.njk.md
=> feat: journey planner widget pattern

src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk, src/wmnds/patterns/journey-planner/_journey-planner.njk
Fix buttons width on mobile
Fixes #788
=> fix: journey planner & buy a ticket buttons

src/wmnds/patterns/footer/_example.js
=> fix: remove deprecated 'addListener' in footer js

src/wmnds/components/form-elements/radios/_radios.njk
=> fix: Fix accessibility issue with radios.

src/wmnds/components/disruption-indicator/medium/_medium.scss, src/wmnds/patterns/travel-updates/_travel-updates.njk, src/wmnds/patterns/travel-updates/_travel-updates.scss
- Changed disruption indicators to displayNarrow
- minor styling amendments to disruption indicator and delete button
fixes #787
=> fix: update travel updates widget styling

src/www/pages/components/buttons/index.njk.md
- Added open all/close all section to buttons component page
fixes #794
=> feat: add accordion buttons to component page

src/wmnds/components/icon/n-icon/_n-icon.scss
=> fix: make n-icon inherit and color & font-weight

src/wmnds/patterns/branded-banner/_branded-banner.njk, src/wmnds/patterns/branded-banner/_branded-banner.scss, src/wmnds/patterns/branded-banner/_example.njk, src/www/pages/patterns/banner/index.njk.md
Fix #832 
Design page link: https://www.figma.com/file/PDLwmCZgpcrI6hfIHKYLku/New-Swift-Custom-Pages?node-id=515%3A373
=> feat: Adding transport modals to branded banner

src/www/pages/styles/a-to-z-content-style-guide/_a-to-z-content-style-guide.njk.json
=> fix: A to Z guide - copy amends

src/wmnds/patterns/buy-a-ticket/_buy-a-ticket.njk, src/wmnds/patterns/buy-a-ticket/_example.js, src/wmnds/patterns/buy-a-ticket/_example.njk, src/www/pages/patterns/buy-a-ticket/index.njk.md
- Add js to buy a ticket page
- Update HTML of buy a ticket component (dropdowns options and values are now up to date)
- Add .njk example
- Matching with umbraco. 
- Can be now used in other websites (HTML + css + js)
=> fix: update buy a ticket

src/wmnds/patterns/find-a-timetable-widget/_example.js, src/wmnds/patterns/find-a-timetable-widget/_find-a-timetable-widget.njk, src/www/pages/patterns/find-a-timetable/index.njk.md
- Matching with umbraco.
- Can be now used in other websites (HTML + css + js)
**Updated files:**
=> fix: update find a timetable widget

src/wmnds/assets/sass/styles/_utilities.scss, src/wmnds/patterns/branded-banner/_branded-banner.scss, src/www/pages/components/buttons/index.njk.md
=> feat: Add Pay with Swift button to buttons page

src/wmnds/patterns/branded-banner/_branded-banner.scss
https://designsystem.tfwm.org.uk/patterns/banner/
=> fix: Fix bug with swift logo size.

src/wmnds/patterns/journey-planner-widget/_journey-planner-widget.njk, src/www/pages/patterns/journey-planner/index.njk.md
=> feat: add jp sidebar widget section
